version: '3.1'
services:
  app:
    container_name: guestbook-compose
    image: iesgn/guestbook
    restart: always
    ports:
      - 80:8080
  db:
    container_name: redis-compose
    image: redis
    restart: always